export const FETCH_CONFIGURATION = "FETCH_CONFIGURATION";
export const FETCH_FILMS = "FETCH_FILMS";
export const FETCH_PEOPLE = "FETCH_PEOPLE";

export const UPDATE_PAGE = "UPDATE_PAGE";
export const UPDATE_SORTTYPE = "UPDATE_SORTTYPE";
export const UPDATE_YEAR = "UPDATE_YEAR";